### ISSUE TITLE
Switch from `eslint-plugin-jsx-expressions` to `@eslint-react/no-leaked-conditional-rendering`

### ISSUE THREAD

**Issue by karlhorky** [upleveled/eslint-config-upleveled#413]
Since `eslint-plugin-jsx-expressions` is not being maintained as much and doesn't support ESLint v9, switch `eslint-plugin-jsx-expressions` to [the `@eslint-react/no-leaked-conditional-rendering` rule](https://eslint-react.xyz/docs/rules/no-leaked-conditional-rendering)

- https://github.com/hluisson/eslint-plugin-jsx-expressions/pull/17#issuecomment-2312951436

Then the `vendor` directory can be removed

And `eslint-config-upleveled` can be added to the "Who is Using" list:

- https://github.com/Rel1cx/eslint-react#who-is-using

<details>
  <summary>Show original issue</summary>

Title: Consider switching from `eslint-plugin-jsx-expressions` to `@typescript-eslint/strict-boolean-expressions`

Since `eslint-plugin-jsx-expressions` is not being maintained as much and doesn't support ESLint v9, consider switching from `eslint-plugin-jsx-expressions` to [`@typescript-eslint/strict-boolean-expressions`](https://typescript-eslint.io/rules/strict-boolean-expressions/)

- https://github.com/hluisson/eslint-plugin-jsx-expressions/pull/17#issuecomment-2294835097

Then the `vendor` directory can be removed

Could be a downside for students though, since it will be reported also on `if` conditions 

[`typescript-eslint` Playground](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=DYUwLgBAdgrgthAvBADAbgFCkgZzAJyQgHJjMMBLAMwgApYEAyRkgD2IEoIBvCAXyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZfKsugIwHs%2BSAIZN6AD2LQUySnyaoMAbUiJo0PtEgAaTOGw4h8eHwDuAZU7MA5ujAAzQ8kRa9%2ByIeMmAcrAC2PVVsHeCdXMABfAF09cJBwoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

![Screenshot 2024-08-17 at 13 59 42](https://github.com/user-attachments/assets/b721849e-7291-4d31-8018-96de3b2f14f5)

</details>

**Comment by ProchaLu** [comment]
.
