### ISSUE TITLE
create-react-app: Cannot read property 'ScopeType' of undefined

### ISSUE THREAD

**Issue by karlhorky** [upleveled/eslint-config-upleveled#56]
When using `create-react-app` with the following setup instructions, the error below occurs:

Instructions:

```
yarn create react-app my-app

cd my-app

CI=true npx install-peerdeps@latest --yarn --dev @upleveled/eslint-config-upleveled
cp node_modules/@upleveled/eslint-config-upleveled/templates/{*,.eslint*} .
touch .gitignore && grep -Fxq ".eslintcache" .gitignore || echo ".eslintcache" >> .gitignore

yarn upgrade react-scripts
```

Error:

```
Failed to compile

Error while loading rule '@typescript-eslint/naming-convention': Cannot read property 'ScopeType' of undefined

Occurred while linting /Users/k/p/my-app/src/index.js
```

<img width="768" alt="Screen Shot 2021-06-21 at 11 05 27" src="https://user-images.githubusercontent.com/1935696/122739364-3106a580-d283-11eb-9c00-1228a141cd74.png">

**Comment by karlhorky** [comment]
This seems to be caused by the following dependency chain: `react-scripts@4.0.3 > eslint-plugin-testing-library@^3.9.2 > @typescript-eslint/experimental-utils@^3.10.1`

**Comment by karlhorky** [comment]
We are addressing it with [Yarn Resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/), by adding a resolution like the following in our `package.json`:

```json
  "resolutions": {
    "eslint-plugin-testing-library": "4.12.4"
  }
```

This will force the version `4.12.4` of the package `eslint-plugin-testing-library` to be installed, regardless of what versions other packages are depending on.

See our change here:

https://github.com/upleveled/eslint-config-upleveled/commit/069f62dc616780f7c85e8a14ce634d8ed54e3ffd

This is a workaround and may break things.

There is also a pull request to upgrade this dependency in `react-scripts` itself: https://github.com/facebook/create-react-app/pull/10817

**Comment by mimoid-prog** [comment]
This error happened to me out of nowhere.
Removing `node_modules` and installing packages again fixes it.

**Comment by brenmoss** [comment]
> This error happened to me out of nowhere. Removing `node_modules` and installing packages again fixes it.

This has been causing me issues for a while now... I found a weird solution where saving an unchanged css modules file allowed a watched build to succeed and the error goes away until I edit a ts file... then save an unchanged css module and the watcher builds and so on...

Turns out I too needed to remove the node_modules and install again and the problem is now solved.. thank you for this solution!
